// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySn38errC9RtIgc8Qo0_dGgh4ybXwNZE',
    appId: '1:663676371710:web:27327e72ff0e223a5e9baf',
    messagingSenderId: '663676371710',
    projectId: 'fir-8e5d6',
    authDomain: 'fir-8e5d6.firebaseapp.com',
    storageBucket: 'fir-8e5d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3h5g2eFoaLxB2FHIoQJ1qVE2sweMCiK8',
    appId: '1:663676371710:android:f55dcb97d17c44945e9baf',
    messagingSenderId: '663676371710',
    projectId: 'fir-8e5d6',
    storageBucket: 'fir-8e5d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC11KrPSBVGXFjycdM239sEXWLVOXFpV5c',
    appId: '1:663676371710:ios:cad9ffc0b24efca25e9baf',
    messagingSenderId: '663676371710',
    projectId: 'fir-8e5d6',
    storageBucket: 'fir-8e5d6.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC11KrPSBVGXFjycdM239sEXWLVOXFpV5c',
    appId: '1:663676371710:ios:cad9ffc0b24efca25e9baf',
    messagingSenderId: '663676371710',
    projectId: 'fir-8e5d6',
    storageBucket: 'fir-8e5d6.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySn38errC9RtIgc8Qo0_dGgh4ybXwNZE',
    appId: '1:663676371710:web:114bd3da2d5e03405e9baf',
    messagingSenderId: '663676371710',
    projectId: 'fir-8e5d6',
    authDomain: 'fir-8e5d6.firebaseapp.com',
    storageBucket: 'fir-8e5d6.appspot.com',
  );
}
